version: "3"
services:
  web:
    image: book-monkey
    env_file:
      - ./docker.env
    ports:
      - "8093:80"
    command: /bin/bash -c "envsubst '$$API_URL' < /usr/share/nginx/html/settings.template.json > /usr/share/nginx/html/settings.json && exec nginx -g 'daemon off;'"
